Repository 2-CM/Ohouse, pull requests merged in 2025-04, with the labels that each got.

#24 refactor: Home - Header (Mobile) 섹션 수정 완료
  src/assets/icons/header/cart-icon.png
  src/assets/icons/header/download-icon.png
  src/assets/icons/header/dropdown-close-btn.png
  src/assets/icons/header/dropdown-icon.png
  src/assets/icons/header/menu-btn.png
  src/assets/icons/header/navigation__home-icon.png
  src/assets/icons/header/navigation__store-icon.png
  src/assets/icons/header/navigation__truck-icon.png
  src/assets/icons/header/search-icon.png
  src/assets/icons/header/search__clear-icon.png
  src/assets/icons/icon-chevron-down.png
  src/assets/icons/icon-chevron-up.png
  src/css/includes/header.css
  src/includes/header.html
  src/js/includes/header.js
Labels: ✨feat, ♻️refactor, 🎨 style

#25 feat: Home - InteriorCollections (Mobile) 섹션 구현 완료
  src/assets/icons/arrow-right-icon.png
  src/assets/icons/more-arrow-right.svg
  src/assets/icons/plus-icon.svg
  src/assets/images/community/home/interior-collections/ic-post-01.avif
  src/assets/images/community/home/interior-collections/ic-post-02.avif
  src/assets/images/community/home/interior-collections/ic-post-03.avif
  src/assets/images/community/home/interior-collections/ic-post-04.avif
  src/css/pages/community/home.css
  src/js/pages/community/home.js
  src/pages/community/home.html
Labels: ✨feat, 🎨 style

#28 Fix: appBanner 사라진 후 헤더 정렬 깨짐 및 공간 유지 버그 해결
  src/css/includes/header.css
  src/includes/app-promotion.html
  src/includes/header.html
  src/js/includes/app-promotion.js
  src/js/includes/header.js
Labels: 🐛fixBug, ✨feat, ♻️refactor

#30 fix: 앱 배너 닫기 후 화면에 바로 반영되지 않던 버그 해결
  src/js/includes/app-promotion.js
Labels: 🐛fixBug

#35 feat: Home - Footer 반응형 구현 완료 (min-width: 768px)
  src/assets/icons/footer/footer__top-chevron.png
  src/assets/images/footer/footer__isms.png
  src/assets/images/footer/footer__iso27001.png
  src/assets/images/footer/footer__pcr.png
  src/css/includes/footer.css
  src/includes/footer.html
  src/js/includes/footer.js
Labels: ✨feat, ♻️refactor, 🎨 style

#32 feat: Home - Header 반응형 구현 완료 (min-width: 768px)
  src/assets/icons/header/write1.svg
  src/assets/icons/header/write2.svg
  src/assets/icons/header/write3.svg
  src/assets/icons/header/write4.svg
  src/assets/icons/header/write5.svg
  src/css/includes/header.css
  src/includes/header.html
  src/js/includes/header.js
Labels: ✨feat, 🎨 style

#36 feat : Home - Banner 반응형 구현 완료 (min-width: 768px)
  src/assets/images/community/home/banners/banner-main-01.png
  src/assets/images/community/home/banners/banner-main-02.png
  src/assets/images/community/home/banners/banner-main-03.png
  src/assets/images/community/home/banners/banner-main-04.png
  src/assets/images/community/home/banners/banner-main-05.png
  src/assets/images/community/home/banners/banner-main-06.png
  src/assets/images/community/home/banners/banner-main-07.png
  src/assets/images/community/home/banners/banner-main-08.png
  src/assets/images/community/home/banners/banner-main-09.png
  src/assets/images/community/home/banners/banner-main-10.png
  src/assets/images/community/home/banners/banner-main-11.png
  src/assets/images/community/home/banners/banner-main-12.png
  src/assets/images/community/home/banners/banner-main-13.png
  src/assets/images/community/home/banners/banner-main-mobile-01.png
  src/assets/images/community/home/banners/banner-main-mobile-02.png
  src/assets/images/community/home/banners/banner-main-mobile-03.png
  src/assets/images/community/home/banners/banner-main-mobile-04.png
  src/assets/images/community/home/banners/banner-main-mobile-05.png
  src/assets/images/community/home/banners/banner-main-mobile-06.png
  src/assets/images/community/home/banners/banner-main-mobile-07.png
  src/assets/images/community/home/banners/banner-main-mobile-08.png
  src/assets/images/community/home/banners/banner-main-mobile-09.png
  src/assets/images/community/home/banners/banner-main-mobile-10.png
  src/assets/images/community/home/banners/banner-main-mobile-11.png
  src/assets/images/community/home/banners/banner-main-mobile-12.png
  src/assets/images/community/home/banners/banner-main-mobile-13.png
  src/assets/images/community/home/banners/banner-main1.avif
  src/assets/images/community/home/banners/banner-main13.avif
  src/assets/images/community/home/banners/banner-main14.avif
  src/assets/images/community/home/banners/banner-main2.avif
  src/assets/images/community/home/banners/banner-main3.avif
  src/assets/images/community/home/banners/banner-main4.avif
  src/assets/images/community/home/banners/banner-main5.avif
  src/assets/images/community/home/banners/banner-main9.avif
  src/assets/images/community/home/banners/banner-preview-user-image.avif
  src/assets/images/community/home/banners/banner-preview-user-profile.jpg
  src/assets/images/community/home/banners/banner-preview.avif
  src/assets/images/community/home/banners/banner-preview.jpg
  src/css/pages/community/home.css
  src/js/pages/community/home.js
  src/pages/community/home.html
Labels: ✨feat, ♻️refactor, 🎨 style
