Repository 2-CM/Ohouse, pull requests merged in 2025-03, with the labels that each got.

#2 Docs: 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/bug-report--template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/refactoring-template.md
Labels: 📑docs

#3 setting: 초기 설정 완료
  .gitignore
  index.html
  src/assets/icons/.gitkeep
  src/assets/images/.gitkeep
  src/css/common/font.css
  src/css/common/reset.css
  src/css/common/theme.css
  src/css/includes/.gitkeep
  src/css/main.css
  src/css/pages/.gitkeep
  src/includes/.gitkeep
  src/js/includes/.gitkeep
  src/js/main.js
  src/js/modules/.gitkeep
  src/js/pages/.gitkeep
  src/pages/.gitkeep
Labels: ⚙️setting

#7 style: 공통 스타일 설정 완료
  src/css/common/font.css
  src/css/common/theme.css
Labels: 🎨 style

#8 feat: Home - Banner 구현 완료
  index.html
  src/assets/icons/plus-icon.svg
  src/assets/images/community/home/banners/banner-main1.avif
  src/assets/images/community/home/banners/banner-main10.avif
  src/assets/images/community/home/banners/banner-main11.avif
  src/assets/images/community/home/banners/banner-main12.avif
  src/assets/images/community/home/banners/banner-main13.avif
  src/assets/images/community/home/banners/banner-main14.avif
  src/assets/images/community/home/banners/banner-main15.avif
  src/assets/images/community/home/banners/banner-main2.avif
  src/assets/images/community/home/banners/banner-main3.avif
  src/assets/images/community/home/banners/banner-main4.avif
  src/assets/images/community/home/banners/banner-main5.avif
  src/assets/images/community/home/banners/banner-main6.avif
  src/assets/images/community/home/banners/banner-main7.avif
  src/assets/images/community/home/banners/banner-main8.avif
  src/assets/images/community/home/banners/banner-main9.avif
  src/assets/images/community/home/banners/banner-preview-user-image.avif
  src/assets/images/community/home/banners/banner-preview.avif
  src/css/main.css
  src/css/pages/community/home.css
  src/js/pages/community/home.js
  src/pages/community/home.html
Labels: ✨feat

#11 feat: Home - QuickMenu (Mobile) 섹션 구현 완료
  src/assets/icons/quick-menu/checkin-icon.png
  src/assets/icons/quick-menu/cleaning-icon.png
  src/assets/icons/quick-menu/daily-deal-icon.png
  src/assets/icons/quick-menu/fast-delivery-icon.png
  src/assets/icons/quick-menu/housewarming-icon.png
  src/assets/icons/quick-menu/living-icon.png
  src/assets/icons/quick-menu/mart-icon.png
  src/assets/icons/quick-menu/remodeling-icon.png
  src/assets/icons/quick-menu/style-icon.png
  src/assets/icons/quick-menu/today-deal-icon.png
  src/css/pages/community/home.css
  src/pages/community/home.html
Labels: ✨feat

#13 feat: Home - Header (Mobile) 섹션 구현 완료
  src/assets/icons/header/cart-icon.png
  src/assets/icons/header/download-icon.png
  src/assets/icons/header/dropdown-close-btn.png
  src/assets/icons/header/dropdown-icon.png
  src/assets/icons/header/header_logo.svg
  src/assets/icons/header/icon-chevron-down.png
  src/assets/icons/header/icon-chevron-up.png
  src/assets/icons/header/menu-btn.png
  src/assets/icons/header/navigation__home-icon.png
  src/assets/icons/header/navigation__store-icon.png
  src/assets/icons/header/navigation__truck-icon.png
  src/assets/icons/header/search-icon.png
  src/assets/icons/header/search__clear-icon.png
  src/css/includes/header.css
  src/css/main.css
  src/includes/header.html
  src/js/includes/header.js
Labels: ✨feat, 🎨 style

#14 feat: Home - Footer (Mobile) 섹션 구현 완료
  src/assets/icons/footer/footer__top-chevron.png
  src/assets/icons/icon-chevron-down.png
  src/assets/icons/icon-chevron-up.png
  src/css/includes/footer.css
  src/css/main.css
  src/includes/footer.html
  src/includes/header.html
  src/js/includes/footer.js
  src/js/includes/header.js
Labels: ✨feat, 🎨 style

#16 feat: Home - InteriorFeed (Mobile) 섹션 구현 완료
  src/assets/icons/arrow-right-icon.png
  src/assets/icons/bookmark-empty.svg
  src/assets/icons/bookmark-filled.svg
  src/assets/icons/more-arrow-right.svg
  src/assets/images/community/home/interior-feeds/interior-post-01-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-01.avif
  src/assets/images/community/home/interior-feeds/interior-post-02-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-02.avif
  src/assets/images/community/home/interior-feeds/interior-post-03-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-03.avif
  src/assets/images/community/home/interior-feeds/interior-post-04-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-04.avif
  src/assets/images/community/home/interior-feeds/interior-post-05-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-05.avif
  src/assets/images/community/home/interior-feeds/interior-post-06-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-06.jpg
  src/assets/images/community/home/interior-feeds/interior-post-07-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-07.avif
  src/assets/images/community/home/interior-feeds/interior-post-08-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-08.jpg
  src/assets/images/community/home/interior-feeds/interior-post-09-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-09.avif
  src/assets/images/community/home/interior-feeds/interior-post-10-profile.avif
  src/assets/images/community/home/interior-feeds/interior-post-10.avif
  src/css/pages/community/home.css
  src/js/pages/community/home.js
  src/pages/community/home.html
Labels: ✨feat, 🎨 style

#18 feat: app-promotion (mobile) 섹션 구현 완료
  src/assets/icons/app-promotion/app-logo.svg
  src/assets/icons/app-promotion/appBanner__close-btn.svg
  src/assets/icons/app-promotion/star.svg
  src/css/includes/app-promotion.css
  src/css/main.css
  src/includes/app-promotion.html
  src/js/includes/app-promotion.js
Labels: ✨feat, 🎨 style

#20 style: 공통 스타일 추가 설정 완료 #6
  src/css/common/theme.css
Labels: 🎨 style

#21 style: 아이콘 폰트 파일 추가 및 설정 완료
  src/assets/fonts/d8923b386a66fd50.woff2
  src/css/common/font.css
Labels: 🎨 style
